### ISSUE TITLE
linuxdeployqt fails on travis

### ISSUE THREAD

**Issue by yschutz** [yschutz/ThermusQt#4]
@probonopd could you help me on this issue ?

The command "./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs" exited with 1.
0.10s$ ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage
linuxdeployqt 4 (commit c01cf77), build 494 built on 2018-03-06 08:39:24 UTC
Desktop file as first argument: "./appdir/usr/share/applications/ThermusQt.desktop"
desktopExecEntry: "ThermusQt"
desktopIconEntry: "ThermusQt"
ERROR: Could not determine the path to the executable based on the desktop file

**Comment by probonopd** [comment]
Does `./appdir/usr/bin/ThermusQt` exist and is it executable?

**Comment by yschutz** [comment]
I find out where the problem is but did not find a solution: 
in ThermusQt.pro -_>
........  
  lib.files      = $$OUT_PWD/ThermusLib/lib/libThermusLib.so
    lib.path       = $$PREFIX/lib

    app.files      = $$OUT_PWD/MainApp/ThermusQt
    app.path       = $$PREFIX/bin

    INSTALLS += icons desktop data python macro header lib app

Neither  $$OUT_PWD/ThermusLib/lib/libThermusLib.so nor $$OUT_PWD/MainApp/ThermusQt
exist when qmake ThermusQt.pro is run. These files are created later. A way around is to run:

qmake ThermusQt.pro
make ----> creates ThermusLib.so and ThermusQt (executable) 
make ThermusQt.pro

But I do not know how to tell travis to do that ...

**Comment by probonopd** [comment]
> But I do not know how to tell travis to do that ...

Add a line

`  - qmake ThermusQt.pro`

**Comment by yschutz** [comment]
... as simple as that ... all problems solved ... Thanks ...
